org.gradle.jvmargs = -Xmx4G

# Mod
minecraft_version = 1.21.1
forge_enabled = true
mod_version = 1.7.3
maven_group = dev.gitcodmaster

# Fabric
fabric_loader_version = 0.16.7

# Forge
forge_version = 52.1.0

# Dependencies
libbulletjme_version = 22.0.3
transporter_version = 1.4.0+1.21.1
toolbox_version = 1.4.0+1.21.1

# Gradle
shadow_version = 8.1.1
loom_version = 1.7-SNAPSHOT
architectury_plugin_version = 3.4-SNAPSHOT
