architectury.common(forge_enabled.toBoolean())

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$fabric_loader_version"
    api "com.github.stephengold:Libbulletjme:$libbulletjme_version"
    modApi "dev.gitcodmaster:transporter-rev2-common:$transporter_version", { transitive false }
    modApi "dev.gitcodmaster:toolbox-common:$toolbox_version", { transitive false }
}
